spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
        - id: movies-service
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/movies/**
    security:
      oauth2:
        client:
          provider:
            api-gateway:
              issuer-uri: http://localhost:8082/realms/digitalmedia
          registration:
            keycloak-spring-gateway-client:
              provider: keycloak
              client-id: api-gateway
              client-secret: CCcioWBeiNnyhCBKyfsmarh7JvPo0Cvf
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

server:
  port: 8080
  
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: API Gateway
