server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute #Identificando la ruta del service de producto
          uri: http://localhost:8086/ #URL donde se har치 el redirect segun el predicate definido
          predicates: #Reglas de an치lisis de una request
            - Path=/movies/**
        - id: facturacionRoute #Identificando la ruta del service de producto
          uri: http://localhost:8088/  #URL donde se har치 el redirect segun el predicate definido
          predicates: #Reglas de an치lisis de una request
            - Path=/facturacion/**
        - id: userRoute
          uri:  http://localhost:8087/
          predicates:
            - Path=/user/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: API Gateway
