server:
  port: 8086
  
spring:
  application:
    name: movie-service
  discovery:
    enabled: true
    service-id: config-service
  eureka:
    client:
      enabled: true
      service-url:
        defaultZone: http://localhost:8761/eureka
  data:
    mongodb:
      uri: mongodb://localhost:27017/moviesdb
      username: admin
      password: admin
      database: tp_final_be2
      port: 27017
      host: mongodb #localhost
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/digitalmedia
        registration:
          keycloak:
            client-id: microservicios
            client-secret: 4AOyKGcMfRmXqdHctmcQnXQNQfKQiAqF
            scope: openid
            redirect_uri: http://localhost:8080/*
