server:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: facturacion-service
  discovery:
    enabled: true
    service-id: config-service
  eureka:
    client:
      enabled: true
      service-url:
        defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/digitalmedia
        registration:
          keycloak:
            client-id: microservicios
            client-secret: 4AOyKGcMfRmXqdHctmcQnXQNQfKQiAqF
            authorization-grand-type: client_credentials
            scope: openid
            redirect_uri: http://localhost:8080/*
            token-uri: http://localhost:8082/realms/digital-house/protocol/openid-connect/token

